use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::paths;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub version: String,
    pub paths: PathsConfig,
    pub server: ServerConfig,
    /// LLM configuration for vision features
    /// Uses serde default for backward compatibility with existing configs
    #[serde(default)]
    pub llm: LlmConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathsConfig {
    pub server_binary: PathBuf,
    pub model_dir: PathBuf,
    pub samples_dir: PathBuf,
    pub espeak_data_dir: PathBuf,
    pub log_dir: PathBuf,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    pub port: u16,
    pub pool_size: usize,
    pub log_level: String,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            port: 3000,
            pool_size: 2,
            log_level: "info".to_string(),
        }
    }
}

/// LLM configuration for vision/AI features
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmConfig {
    /// Active LLM provider: "gemini" or "openai"
    /// None means auto-select based on configured keys (prefer gemini)
    pub active_provider: Option<String>,
}

impl Default for LlmConfig {
    fn default() -> Self {
        Self {
            active_provider: None,
        }
    }
}

impl LlmConfig {
    /// Validate that the provider is a valid option
    pub fn is_valid_provider(provider: &str) -> bool {
        matches!(provider.to_lowercase().as_str(), "gemini" | "openai")
    }

    /// Set the active provider with validation
    pub fn set_active_provider(&mut self, provider: Option<String>) -> Result<()> {
        if let Some(ref p) = provider {
            if !Self::is_valid_provider(p) {
                return Err(anyhow::anyhow!(
                    "Invalid provider '{}'. Must be 'gemini' or 'openai'",
                    p
                ));
            }
        }
        self.active_provider = provider.map(|p| p.to_lowercase());
        Ok(())
    }
}

impl Config {
    /// Create a new config with default values and platform-specific paths
    pub fn new() -> Result<Self> {
        Ok(Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            paths: PathsConfig {
                server_binary: paths::get_server_binary_path()?,
                model_dir: paths::get_models_dir()?,
                samples_dir: paths::get_samples_dir()?,
                espeak_data_dir: paths::get_espeak_data_dir()?,
                log_dir: paths::get_logs_dir()?,
            },
            server: ServerConfig::default(),
            llm: LlmConfig::default(),
        })
    }

    /// Load config from file, or create default if not exists
    pub fn load() -> Result<Self> {
        let config_file = paths::get_config_file()?;

        if config_file.exists() {
            let contents = std::fs::read_to_string(&config_file)
                .context("Failed to read config file")?;

            let config: Config = serde_json::from_str(&contents)
                .context("Failed to parse config file")?;

            Ok(config)
        } else {
            // Create default config
            let config = Self::new()?;
            config.save()?;
            Ok(config)
        }
    }

    /// Save config to file
    pub fn save(&self) -> Result<()> {
        let config_file = paths::get_config_file()?;

        let contents = serde_json::to_string_pretty(&self)
            .context("Failed to serialize config")?;

        std::fs::write(&config_file, contents)
            .context("Failed to write config file")?;

        Ok(())
    }

    /// Save .env file for server binary
    pub fn save_env_file(&self) -> Result<()> {
        let env_file = paths::get_env_file()?;

        // PIPER_ESPEAKNG_DATA_DIRECTORY must point to the PARENT directory containing espeak-ng-data
        // See server/.env.example:L110 for documentation
        let espeak_parent_dir = self.paths.espeak_data_dir
            .parent()
            .context("Failed to get parent directory of espeak_data_dir")?;

        // Create .env file content from config
        let env_content = format!(
            "# Porua Server Environment Configuration\n\
             # Auto-generated by installer\n\
             \n\
             # Model directory path\n\
             TTS_MODEL_DIR={}\n\
             \n\
             # eSpeak-ng data directory (parent directory containing espeak-ng-data/)\n\
             PIPER_ESPEAKNG_DATA_DIRECTORY={}\n\
             \n\
             # Pool size (number of TTS engines)\n\
             TTS_POOL_SIZE={}\n\
             \n\
             # Log level (trace, debug, info, warn, error)\n\
             RUST_LOG={}\n",
            self.paths.model_dir.display(),
            espeak_parent_dir.display(),
            self.server.pool_size,
            self.server.log_level
        );

        std::fs::write(&env_file, env_content)
            .context("Failed to write .env file")?;

        Ok(())
    }

    /// Update server port (for future Phase 2)
    #[allow(dead_code)]
    pub fn set_port(&mut self, port: u16) -> Result<()> {
        self.server.port = port;
        self.save()
    }

    /// Update pool size (for future Phase 2)
    #[allow(dead_code)]
    pub fn set_pool_size(&mut self, pool_size: usize) -> Result<()> {
        self.server.pool_size = pool_size;
        self.save()
    }

    /// Update log level (for future Phase 2)
    #[allow(dead_code)]
    pub fn set_log_level(&mut self, log_level: String) -> Result<()> {
        self.server.log_level = log_level;
        self.save()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = Config::new().unwrap();
        assert_eq!(config.server.port, 3000);
        assert_eq!(config.server.pool_size, 2);
        assert_eq!(config.server.log_level, "info");
    }

    // Phase 2 tests for LlmConfig

    #[test]
    fn test_llm_config_default() {
        let llm_config = LlmConfig::default();
        assert!(llm_config.active_provider.is_none());
    }

    #[test]
    fn test_llm_config_valid_providers() {
        assert!(LlmConfig::is_valid_provider("gemini"));
        assert!(LlmConfig::is_valid_provider("openai"));
        assert!(LlmConfig::is_valid_provider("GEMINI"));
        assert!(LlmConfig::is_valid_provider("OpenAI"));
        assert!(LlmConfig::is_valid_provider("Gemini"));
    }

    #[test]
    fn test_llm_config_invalid_providers() {
        assert!(!LlmConfig::is_valid_provider("claude"));
        assert!(!LlmConfig::is_valid_provider("gpt4"));
        assert!(!LlmConfig::is_valid_provider(""));
        assert!(!LlmConfig::is_valid_provider("invalid"));
    }

    #[test]
    fn test_llm_config_set_active_provider_valid() {
        let mut llm_config = LlmConfig::default();

        // Set to gemini
        let result = llm_config.set_active_provider(Some("gemini".to_string()));
        assert!(result.is_ok());
        assert_eq!(llm_config.active_provider, Some("gemini".to_string()));

        // Set to openai
        let result = llm_config.set_active_provider(Some("OpenAI".to_string()));
        assert!(result.is_ok());
        assert_eq!(llm_config.active_provider, Some("openai".to_string())); // Normalized to lowercase

        // Set to None
        let result = llm_config.set_active_provider(None);
        assert!(result.is_ok());
        assert!(llm_config.active_provider.is_none());
    }

    #[test]
    fn test_llm_config_set_active_provider_invalid() {
        let mut llm_config = LlmConfig::default();

        let result = llm_config.set_active_provider(Some("invalid".to_string()));
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("Invalid provider"));
    }

    #[test]
    fn test_config_includes_llm_field() {
        let config = Config::new().unwrap();
        assert!(config.llm.active_provider.is_none());
    }

    #[test]
    fn test_config_serialization_includes_llm() {
        let config = Config::new().unwrap();
        let json = serde_json::to_string(&config).unwrap();

        // Verify llm field is in serialized output
        assert!(json.contains("\"llm\""));
        assert!(json.contains("\"active_provider\""));
    }

    #[test]
    fn test_config_deserialization_without_llm_field() {
        // Simulate an old config file without the llm field
        // This tests backward compatibility
        let old_config_json = r#"{
            "version": "0.1.0",
            "paths": {
                "server_binary": "/tmp/server",
                "model_dir": "/tmp/models",
                "samples_dir": "/tmp/samples",
                "espeak_data_dir": "/tmp/espeak",
                "log_dir": "/tmp/logs"
            },
            "server": {
                "port": 3000,
                "pool_size": 2,
                "log_level": "info"
            }
        }"#;

        let config: Result<Config, _> = serde_json::from_str(old_config_json);
        assert!(config.is_ok(), "Failed to deserialize old config: {:?}", config.err());

        let config = config.unwrap();
        // llm should use default values
        assert!(config.llm.active_provider.is_none());
    }

    #[test]
    fn test_config_deserialization_with_llm_field() {
        let config_json = r#"{
            "version": "0.1.0",
            "paths": {
                "server_binary": "/tmp/server",
                "model_dir": "/tmp/models",
                "samples_dir": "/tmp/samples",
                "espeak_data_dir": "/tmp/espeak",
                "log_dir": "/tmp/logs"
            },
            "server": {
                "port": 3000,
                "pool_size": 2,
                "log_level": "info"
            },
            "llm": {
                "active_provider": "gemini"
            }
        }"#;

        let config: Result<Config, _> = serde_json::from_str(config_json);
        assert!(config.is_ok(), "Failed to deserialize config with llm: {:?}", config.err());

        let config = config.unwrap();
        assert_eq!(config.llm.active_provider, Some("gemini".to_string()));
    }

    #[test]
    fn test_config_deserialization_with_null_provider() {
        let config_json = r#"{
            "version": "0.1.0",
            "paths": {
                "server_binary": "/tmp/server",
                "model_dir": "/tmp/models",
                "samples_dir": "/tmp/samples",
                "espeak_data_dir": "/tmp/espeak",
                "log_dir": "/tmp/logs"
            },
            "server": {
                "port": 3000,
                "pool_size": 2,
                "log_level": "info"
            },
            "llm": {
                "active_provider": null
            }
        }"#;

        let config: Result<Config, _> = serde_json::from_str(config_json);
        assert!(config.is_ok());

        let config = config.unwrap();
        assert!(config.llm.active_provider.is_none());
    }

    #[test]
    fn test_llm_config_roundtrip_serialization() {
        let mut llm_config = LlmConfig::default();
        llm_config.set_active_provider(Some("openai".to_string())).unwrap();

        // Serialize
        let json = serde_json::to_string(&llm_config).unwrap();

        // Deserialize
        let deserialized: LlmConfig = serde_json::from_str(&json).unwrap();

        assert_eq!(llm_config.active_provider, deserialized.active_provider);
    }
}
